"""
Orion Automation — Blog API (FastAPI)
=====================================
Public read API + admin CRUD + image upload/proxy, backed by Google Drive.

Run locally:
  cd OrionAutomation
  uvicorn backend.main:app --reload --port 8000

Public endpoints:
  GET  /api/blogs                       list published posts
  GET  /api/blogs/{slug}                fetch one published post
  GET  /api/images/{file_id}            proxy a Drive image (no auth)

Admin endpoints (Authorization: Bearer <ADMIN_PASSWORD>):
  POST   /api/admin/login               verify username + password
  GET    /api/admin/blogs               list all posts (incl. drafts)
  GET    /api/admin/blogs/{slug}        fetch any post by slug
  POST   /api/admin/blogs               create or upsert a post
  PUT    /api/admin/blogs/{slug}        update a post
  DELETE /api/admin/blogs/{slug}        delete a post
  POST   /api/admin/images              upload an image (multipart/form-data)
  GET    /api/admin/images              list recent images
  GET    /api/admin/mcp-key             fetch current MCP API key (admin only)
  POST   /api/admin/mcp-key/rotate      generate a new MCP API key

MCP server (mounted at /mcp). Auth: Authorization: Bearer <MCP key>, where
the key is generated by the admin in the CMS. The MCP endpoint is unusable
until the admin clicks "Generate" once.
"""

from __future__ import annotations

import os
import re
import unicodedata
from datetime import date
from pathlib import Path
from typing import Any, Literal

from dotenv import load_dotenv
from fastapi import (
    Depends,
    FastAPI,
    File,
    HTTPException,
    Response,
    UploadFile,
    status,
)
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

# Load env from project root (one level up from backend/)
load_dotenv(Path(__file__).parent.parent / ".env")

from backend import keys
from backend.auth import require_admin, verify_admin_login
from backend.drive_storage import get_storage
from backend.mcp_server import mcp as mcp_server, mcp_asgi_app

# ─── App ──────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Orion Blog API",
    description="Blog backend with admin CMS and MCP automation interface, backed by Google Drive.",
    version="2.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://localhost:3000",
        "https://orionautomation.xyz",
        "https://www.orionautomation.xyz",
    ],
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers=["*"],
)

# Mount the MCP HTTP server at /mcp. Authentication is enforced inside
# mcp_server via a middleware on the mounted Starlette app.
app.mount("/mcp", mcp_asgi_app)


# ─── Schemas ──────────────────────────────────────────────────────────────────

SectionType = Literal["p", "h2", "h3", "ul", "ol", "quote", "cta", "img"]


class Section(BaseModel):
    type: SectionType
    text: str | None = None
    items: list[str] | None = None
    cite: str | None = None
    to: str | None = None
    label: str | None = None
    src: str | None = None
    alt: str | None = None
    caption: str | None = None


class PostIn(BaseModel):
    slug: str | None = None
    title: str
    description: str = ""
    keywords: str = ""
    author: str = "Orion Automation Team"
    category: str = "General"
    readMinutes: int = Field(default=5, ge=1, le=60)
    publishedAt: str | None = None
    updatedAt: str | None = None
    cover: str = "#E6A520"
    coverImage: str | None = None
    excerpt: str = ""
    status: Literal["draft", "published"] = "draft"
    sections: list[Section] = Field(default_factory=list)


class LoginIn(BaseModel):
    username: str
    password: str


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _slugify(text: str) -> str:
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    text = re.sub(r"\s+", "-", text.strip())
    text = re.sub(r"-+", "-", text)
    return text[:80] or "post"


def _normalize_post(data: dict) -> dict:
    if not data.get("slug"):
        data["slug"] = _slugify(data.get("title", "post"))
    if not data.get("publishedAt"):
        data["publishedAt"] = date.today().isoformat()
    if not data.get("updatedAt"):
        data["updatedAt"] = date.today().isoformat()
    if not data.get("excerpt") and data.get("description"):
        data["excerpt"] = data["description"]
    data["sections"] = data.get("sections") or []
    return data


# ─── Public routes ────────────────────────────────────────────────────────────

@app.get("/")
def root():
    return {"message": "Orion Blog API is running", "version": "2.0.0"}


@app.get("/healthz")
def healthz():
    return {"ok": True}


@app.get("/api/blogs")
def list_blogs():
    """List all published posts, newest first."""
    posts = get_storage().list_posts(include_drafts=False)
    return {"posts": posts, "total": len(posts)}


@app.get("/api/blogs/{slug}")
def get_blog(slug: str):
    post = get_storage().get_post(slug, include_drafts=False)
    if not post:
        raise HTTPException(status_code=404, detail="Post not found")
    return post


@app.get("/api/images/{file_id}")
def get_image(file_id: str):
    """Proxy a Drive image. Public — anyone with the URL can view."""
    try:
        data, mime = get_storage().download_image(file_id)
    except Exception as e:
        raise HTTPException(status_code=404, detail=f"Image not available: {e}")
    return Response(
        content=data,
        media_type=mime,
        headers={"Cache-Control": "public, max-age=86400"},
    )


# ─── Admin routes ─────────────────────────────────────────────────────────────

@app.post("/api/admin/login")
def admin_login(body: LoginIn):
    if not verify_admin_login(body.username, body.password):
        raise HTTPException(status_code=401, detail="Invalid username or password")
    # The bearer token IS the password — single-admin model. Frontend stores it
    # and sends it as Bearer on subsequent calls.
    return {"ok": True, "token": body.password, "username": body.username}


@app.get("/api/admin/blogs", dependencies=[Depends(require_admin)])
def admin_list_blogs():
    posts = get_storage().list_posts(include_drafts=True)
    return {"posts": posts, "total": len(posts)}


@app.get("/api/admin/blogs/{slug}", dependencies=[Depends(require_admin)])
def admin_get_blog(slug: str):
    post = get_storage().get_post(slug, include_drafts=True)
    if not post:
        raise HTTPException(status_code=404, detail="Post not found")
    return post


@app.post(
    "/api/admin/blogs",
    dependencies=[Depends(require_admin)],
    status_code=status.HTTP_201_CREATED,
)
def admin_create_blog(post: PostIn):
    data = _normalize_post(post.model_dump(exclude_none=False))
    saved = get_storage().save_post(data)
    return saved


@app.put("/api/admin/blogs/{slug}", dependencies=[Depends(require_admin)])
def admin_update_blog(slug: str, post: PostIn):
    data = post.model_dump(exclude_none=False)
    data["slug"] = slug
    data["updatedAt"] = date.today().isoformat()
    data = _normalize_post(data)
    saved = get_storage().save_post(data)
    return saved


@app.delete("/api/admin/blogs/{slug}", dependencies=[Depends(require_admin)])
def admin_delete_blog(slug: str):
    ok = get_storage().delete_post(slug)
    if not ok:
        raise HTTPException(status_code=404, detail="Post not found")
    return {"ok": True}


@app.post("/api/admin/images", dependencies=[Depends(require_admin)])
async def admin_upload_image(file: UploadFile = File(...)):
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="File must be an image")
    content = await file.read()
    if len(content) > 10 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="Image must be under 10 MB")
    safe_name = re.sub(r"[^A-Za-z0-9._-]", "_", file.filename or "image")
    info = get_storage().upload_image(
        filename=safe_name, content=content, mime=file.content_type
    )
    return {
        "id": info["id"],
        "name": info["name"],
        "mime": info["mime"],
        "url": f"/api/images/{info['id']}",
    }


@app.get("/api/admin/images", dependencies=[Depends(require_admin)])
def admin_list_images(limit: int = 50):
    images = get_storage().list_images(limit=limit)
    return {
        "images": [
            {**img, "url": f"/api/images/{img['id']}"} for img in images
        ]
    }


# ─── MCP key management ───────────────────────────────────────────────────────

@app.get("/api/admin/mcp-key", dependencies=[Depends(require_admin)])
def admin_get_mcp_key():
    """Return the current MCP API key and its metadata, or null if not generated yet."""
    meta = keys.get_metadata()
    return meta or {"key": None, "createdAt": None, "rotatedAt": None}


@app.post("/api/admin/mcp-key/rotate", dependencies=[Depends(require_admin)])
def admin_rotate_mcp_key():
    """Generate a brand-new MCP API key. Any previously-stored key stops working."""
    return keys.rotate()


# ─── Error handler ────────────────────────────────────────────────────────────

@app.exception_handler(RuntimeError)
async def runtime_error_handler(_request, exc: RuntimeError):
    return JSONResponse(status_code=500, content={"detail": str(exc)})
